### PR TITLE
Clean up requirements.txt + Add docker

### PR DESCRIPTION
**Pull request by kvn219**
I got the `log_vehicle_positions.py` script to run with docker. Check it out and let me know if it works on your machine.

### CODE REVIEW

**Comment by ctsexton** [comment]
Thanks will check it out. I'm wondering though, what are the advantages of docker when we already have the python environment? I haven't used docker much but happy to go for it if you think it will be a big help!

**Comment by ctsexton** [comment]
I did get this to work on my machine... still not convinced it is necessary. I have read a lot of good arguments for using docker, but in this case I don't see how it is any simpler than the python virtual environment. It also appears that docker is running with root privileges, which I'd rather avoid if possible. What do you think?

**Comment by kvn219** [comment]
All those points sound fair. Docker integration at this stage might be premature.  At a later stage, I recommend we explore docker integration to accommodate contributors with different operating systems.

I'll go ahead and close this merge request.

**Comment by ctsexton** [comment]
Thanks Kevin, yeah I'm definitely open to it a little further down the track - also as a deployment tool.

**Pull request closed without merging**
